#!/usr/bin/env python3
"""Reset one product's price history or all product histories.

Requests are created by the static dashboard as pre-filled GitHub issues. The
workflow invoking this script verifies that the issue author is the repository
owner before any repository data is changed.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LATEST_PATH = ROOT / "data" / "latest.json"
HISTORY_PATH = ROOT / "data" / "price-history.json"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def parse_request(body: str) -> dict[str, str]:
    """Parse the small key/value command block generated by the dashboard."""
    values: dict[str, str] = {}
    for raw_line in body.splitlines():
        key, separator, value = raw_line.partition(":")
        if not separator:
            continue
        key = key.strip().lower()
        if key in {"action", "scope", "product_id", "product_name"}:
            values[key] = value.strip()

    if values.get("action") != "clear-price-history":
        raise ValueError("The issue does not contain a valid clear-price-history action.")
    if values.get("scope") not in {"all", "product"}:
        raise ValueError("The history reset scope must be 'all' or 'product'.")
    if values["scope"] == "product" and not values.get("product_id"):
        raise ValueError("A product reset request must include product_id.")
    return values


def baseline_entry(product: dict[str, Any], latest: dict[str, Any]) -> dict[str, Any] | None:
    price = product.get("price")
    if price is None:
        return None
    return {
        "timestamp": product.get("checked_at") or latest.get("generated_at"),
        "price": price,
        "currency": product.get("currency") or latest.get("currency", "GBP"),
        "in_stock": product.get("in_stock"),
        "reason": "manual-reset",
    }


def reset_product(
    product: dict[str, Any],
    latest: dict[str, Any],
    histories: dict[str, list[dict[str, Any]]],
) -> None:
    product_id = str(product["id"])
    baseline = baseline_entry(product, latest)
    histories[product_id] = [baseline] if baseline else []

    price = product.get("price")
    product["previous_price"] = price
    product["change"] = 0.0 if price is not None else None
    product["change_percent"] = 0.0 if price is not None else None
    product["lowest_price"] = price
    product["highest_price"] = price
    product["history_count"] = len(histories[product_id])
    if baseline and baseline.get("timestamp"):
        product["first_seen_at"] = baseline["timestamp"]


def clear_price_history(
    latest: dict[str, Any],
    histories: dict[str, list[dict[str, Any]]],
    request: dict[str, str],
) -> tuple[bool, str]:
    products = [item for item in latest.get("products", []) if isinstance(item, dict) and item.get("id")]
    if request["scope"] == "all":
        targets = products
        label = "all tracked products"
    else:
        product_id = request["product_id"]
        targets = [item for item in products if str(item.get("id")) == product_id]
        if not targets:
            raise ValueError(f"No tracked product has id '{product_id}'.")
        label = str(targets[0].get("product_name") or product_id)

    for product in targets:
        reset_product(product, latest, histories)

    if not targets:
        return False, "No tracked products were available to reset."
    return True, f"Cleared stored price history for {label}. A current-price baseline was retained."


def set_output(name: str, value: str) -> None:
    output_path = os.environ.get("GITHUB_OUTPUT")
    if output_path:
        with open(output_path, "a", encoding="utf-8") as handle:
            handle.write(f"{name}={value}\n")
    else:
        print(f"OUTPUT {name}={value}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--request-file", type=Path, required=True)
    args = parser.parse_args()

    request = parse_request(args.request_file.read_text(encoding="utf-8"))
    latest = load_json(LATEST_PATH, {})
    histories = load_json(HISTORY_PATH, {})
    changed, summary = clear_price_history(latest, histories, request)

    if changed:
        write_json(LATEST_PATH, latest)
        write_json(HISTORY_PATH, histories)

    set_output("changed", str(changed).lower())
    set_output("summary", summary.replace("\n", " "))
    print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
